version: '3.7'

#Banco de Dados
services:
  mysql: 
    image: mysql:5.7
    networks:
      - network-zabbix  
    ports:
      - '3306:3306' 
    volumes:
      - '/var/lib/docker/volumes/portainer_portainer_data/_data/ZABIX/Mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456    
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
      replicas: 1
    
#Zabix SERVER
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix     
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - '/var/lib/docker/volumes/portainer_portainer_data/_data/ZABIX/Alertscripts/:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
      replicas: 1      
        
  zabbix-frontend: 
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix     
    links:
      - mysql
    restart: always
    ports:
      - '8180:8080'
      - '443:8443' 
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
      replicas: 1     

# GRAFANA 
  grafana:  
    image: grafana/grafana
    networks:
      - network-zabbix    
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000' 
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql
      - zabbix-server
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
      replicas: 1     

#Agent ZABIX 
  zabbix-agent: 
    image: zabbix/zabbix-agent2:alpine-5.0.1
    networks:
      - network-zabbix      
    user: root
    links:
      - zabbix-server
    restart: always
    privileged: true      
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=192.168.181.10
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      resources:
        limits:
          cpus: "0.25"
          memory: 64M

#Configurações Gerais
volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.181.21,rw
      device: ":/STG/PORTAINER"

networks:
  network-zabbix:
    driver: bridge
    attachable: true