version: '3.7'
services:
  zookeeperr01:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeperr01
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    networks:
      - network_overlay
    extra_hosts:
      - "moby:127.0.0.1"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
      replicas: 2

  zookeeperr02:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeperr02    
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
      replicas: 2          

  zookeeperr03:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeperr03    
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    networks:
      - network_overlay
    extra_hosts:
      - "moby:127.0.0.1"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
      replicas: 2          

  kafka01:
    image: confluentinc/cp-kafka:latest
    container_name: kafka01    
    network_mode: host
    networks:
      - network_overlay
    depends_on:
      - zookeeperr01
      - zookeeperr02
      - zookeeperr03
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
    extra_hosts:
      - "moby:127.0.0.1"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
      replicas: 2          

  kafka02:
    image: confluentinc/cp-kafka:latest
    container_name: kafka02    
    network_mode: host
    networks:
      - network_overlay
    depends_on:
      - zookeeperr01
      - zookeeperr02
      - zookeeperr03
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
    extra_hosts:
      - "moby:127.0.0.1"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
      replicas: 2          

  kafka03:
    image: confluentinc/cp-kafka:latest
    container_name: kafka03    
    network_mode: host
    networks:
      - network_overlay
    depends_on:
      - zookeeperr01
      - zookeeperr02
      - zookeeperr03
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
    extra_hosts:
      - "moby:127.0.0.1"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
      replicas: 2          

#Configurações Gerais
volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.181.21,rw
      device: ":/STG/PORTAINER"

networks:
  network_overlay:
    driver: overlay
    ipam:
      config:
      - subnet: 10.255.0.0/16
    attachable: true
  network-zabbix:
    driver: bridge
    attachable: true